### ISSUE TITLE
:label: [CommonController] Implement GET /me endpoint

### ISSUE THREAD

**Issue by VladOSIO2** [CalculusEnjoyer/intellistart-java-2022-vanquishers#101]
Can only be done once the authorisation will be fully implemented

Implement GET /me endpoint for getting information about the current user in CommonController
`GET /me`
Response:
```
{
    "email": "your@email.com",
    "role": "INTERVIEWER",
    "id": "some-UUID-only-for-COORDINATOR-or-INTERVIEWER"
}
```
For the Guest, response should be same as for any other endpoint, not allowed for Guests:
```
HTTP 403
{
    "errorCode": "not_authorized",
    "errorMessage": "You are not authorized to use this functionality"
}
```

**Comment by grata-salve** [comment]
Endpoint was realized and returns the following data:
![image](https://user-images.githubusercontent.com/80597907/204090442-8f4acea9-faba-4806-889b-2f8360a47554.png)
