### ISSUE TITLE
Refactor TimeSlot into InterviewerSlot: 0.1h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#13]
Refactor TimeSlot into InterviewerSlot and implement its fields

**Comment by grata-salve** [comment]
![image](https://user-images.githubusercontent.com/80597907/194546850-48d21513-0fcf-4456-866e-a98de71a2e46.png)

**Comment by CalculusEnjoyer** [comment]
Refactor TimeSlot into InterviewerSlot according to database diagram: https://lucid.app/lucidchart/4bb30bc9-e610-48ff-aed1-10c51d0ea3c2/edit?viewport_loc=-138%2C-157%2C2750%2C1315%2C0_0&invitationId=inv_2fd643b4-d10e-44c3-a200-cc4a6277a571#

**Comment by grata-salve** [comment]
:recycle: Refactored and cleaned up.
