### ISSUE TITLE
Implement CandidateSlot entity: 1h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#14]
Create CandidateSlot class and implement its fields

**Comment by grata-salve** [comment]
![image](https://user-images.githubusercontent.com/80597907/194546920-9d95c7e3-91ab-4186-8ef9-b70f2de07ec3.png)

**Comment by CalculusEnjoyer** [comment]
Create CandidateSlot class and implement its fields according to database diagram: https://lucid.app/lucidchart/4bb30bc9-e610-48ff-aed1-10c51d0ea3c2/edit?viewport_loc=-138%2C-157%2C2750%2C1315%2C0_0&invitationId=inv_2fd643b4-d10e-44c3-a200-cc4a6277a571#
