### ISSUE TITLE
Implement Booking entity: 1h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#15]
Create Booking class and implement its fields

**Comment by grata-salve** [comment]
![image](https://user-images.githubusercontent.com/80597907/194546974-4316bf7d-5075-42a1-ab65-8a4186bb2c60.png)

**Comment by CalculusEnjoyer** [comment]
Create Booking class and implement its fields.

**Comment by grata-salve** [comment]
:sparkles:A preliminary version of the entity has been created.
