### ISSUE TITLE
Implement Interviewer controller: 2h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#19]
Implement endpoints:

  - create or update time slots for next week
  - get own current week time slots
  - get own next week time slots
  - set the maximum number of bookings for next week

**Comment by VladOSIO2** [comment]
Template class with all endpoint templates was implemented in #52 

All the endpoints implementation was decomposed into different issues:

- create time slot for next week: #73 
- update time slot for next week: #74 
- get own current week time slots: #75 
- get own next week time slots: #77 
- set the maximum number of bookings for next week: #76
