### ISSUE TITLE
Implement Coordinator controller: 3h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#20]
Implement endpoints:

  - get all the candidates and interviewers slots (GET /weeks/{weekId}/dashboard)
  - update any Interviewer's time slot (next week or current week) (POST /interviewers/{interviewerId}/slots/{slotId})
  - create booking (POST /bookings)
  - update any booking (POST /bookings/{bookingId})
  - delete booking (DELETE /bookings/{bookingId})
  - grant the Interviewer role providing the E-mail of user (POST /users/interviewers)
  - list the granted Interviewers (GET /users/interviewers)
  - revoke the Interviewer role (DELETE /users/interviewers/<interviewer-id>)
  - grant the Coordinator role providing the E-mail of user (POST /users/coordinators)
  - list the granted Coordinators (GET /users/coordinators)
  - revoke the Coordinator role (DELETE /users/coordinators/<coordinator-id>)

**Comment by VladOSIO2** [comment]
Template class with all endpoint templates was implemented in #46

All the endpoints implementation was decomposed into different issues: 
- get all the candidates and interviewers slots (GET /weeks/{weekId}/dashboard): #60
- update any Interviewer's time slot (next week or current week) (POST /interviewers/{interviewerId}/slots/{slotId}): moved to InterviewerController
- create booking (POST /bookings): #61 
- update any booking (POST /bookings/{bookingId}): #62 
- delete booking (DELETE /bookings/{bookingId}): #63 
- grant the Interviewer role providing the E-mail of user (POST /users/interviewers): #64 
- list the granted Interviewers (GET /users/interviewers): #65 
- revoke the Interviewer role (DELETE /users/interviewers/): #66 
- grant the Coordinator role providing the E-mail of user (POST /users/coordinators): #67 
- list the granted Coordinators (GET /users/coordinators): #68 
- revoke the Coordinator role (DELETE /users/coordinators/): #69
