### ISSUE TITLE
Implement Candidate Controller: 3h

### ISSUE THREAD

**Issue by CalculusEnjoyer** [CalculusEnjoyer/intellistart-java-2022-vanquishers#23]
Candidate can create one or more availability Slots (`POST /candidates/current/slots`):
- Slot must be in future
- Slot has to be 1.5 hours or more and rounded to 30 minutes
- Slot is defined as exact date and time diapason (not like Interviewer slot, where day of week and week number are used)

Candidate can update own slots only if there is no bookings (`POST /candidates/current/slots/{slotId}`)

Candidate can see all own slots: `GET /candidates/current/slots`
- each slot contains the list of bookings in this slot, if any

**Comment by VladOSIO2** [comment]
Template class with all endpoint templates was implemented in https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/pull/46

All the endpoints implementation was decomposed into different issues:
- Candidate can create one or more availability Slots (POST /candidates/current/slots): #78 
- Candidate can update own slots only if there is no bookings (PUT /candidates/current/slots/{slotId}): #79 
- Candidate can see all own slots (GET /candidates/current/slots): #81
