### ISSUE TITLE
Implement Interviewer service: 3h

### ISSUE THREAD

**Issue by Archasmiel** [CalculusEnjoyer/intellistart-java-2022-vanquishers#28]

**Comment by Archasmiel** [comment]
![image](https://user-images.githubusercontent.com/95091020/194594640-ffe88909-1257-40bb-aa10-bfec952566d3.png)

**Comment by VladOSIO2** [comment]
Created in #4, methods implemented in various PRs (https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/commits/main/src/main/java/com/intellias/intellistart/interviewplanning/services/InterviewerService.java) when the functional logic and other requirements were implemented.
