### ISSUE TITLE
Implement Candidate service: 3h

### ISSUE THREAD

**Issue by Archasmiel** [CalculusEnjoyer/intellistart-java-2022-vanquishers#29]

**Comment by Archasmiel** [comment]
![image](https://user-images.githubusercontent.com/95091020/194594761-08341b5f-2ece-45a8-b1d7-44c63ecb853a.png)

**Comment by VladOSIO2** [comment]
Created in #4, methods implemented through various PRs (can be seen in https://github.com/CalculusEnjoyer/intellistart-java-2022-vanquishers/commits/main/src/main/java/com/intellias/intellistart/interviewplanning/services/CandidateService.java) when they were needed to implement functional requirements.
