### ISSUE TITLE
Complete Interviewer entity: 1h

### ISSUE THREAD

**Issue by olexandra-shokotko** [CalculusEnjoyer/intellistart-java-2022-vanquishers#7]

**Comment by Archasmiel** [comment]
![image](https://user-images.githubusercontent.com/95091020/194326323-979c8183-135b-4cdb-a21a-13ab8cdf8de3.png)

**Comment by grata-salve** [comment]
![image](https://user-images.githubusercontent.com/80597907/194546682-36e64920-d764-45bd-972a-14b1e4abd36a.png)

**Comment by grata-salve** [comment]
:sparkles:A preliminary version of the entity has been created.
